# Generated by Django 5.2.7 on 2025-10-29 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='insignias',
            fields=[
                ('id_insignia', models.AutoField(db_column='id_insignia', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('icono', models.CharField(db_column='icono', max_length=255)),
                ('tipo', models.CharField(db_column='tipo', max_length=30)),
                ('criterio', models.CharField(db_column='criterio', max_length=255)),
                ('puntos', models.IntegerField(db_column='puntos')),
                ('color', models.CharField(db_column='color', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'db_table': 'insignias',
            },
        ),
        migrations.CreateModel(
            name='modulos',
            fields=[
                ('id_modulo', models.AutoField(db_column='id_modulo', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('icono', models.CharField(db_column='icono', max_length=100)),
                ('color', models.CharField(db_column='color', max_length=7)),
                ('orden', models.IntegerField(db_column='orden')),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='id_usuario', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('rol', models.CharField(db_column='rol', max_length=50)),
                ('departamento', models.CharField(db_column='departamento', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, db_column='ultima_conexion')),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('foto_perfil', models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='fotos_perfil/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='capacitaciones',
            fields=[
                ('id_capacitacion', models.AutoField(db_column='id_capacitacion', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='descripcion')),
                ('tipo', models.CharField(db_column='tipo', max_length=20)),
                ('nivel', models.CharField(db_column='nivel', max_length=20)),
                ('duracion_horas', models.IntegerField(db_column='duracion_horas')),
                ('url_recurso', models.URLField(db_column='url_recurso', max_length=500)),
                ('tipo_recurso', models.CharField(db_column='tipo_recurso', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_publicacion', models.DateTimeField(blank=True, db_column='fecha_publicacion', null=True)),
                ('estado', models.CharField(db_column='estado', max_length=20)),
                ('puntos_insignia', models.IntegerField(db_column='puntos_insignia')),
                ('thumbnail', models.CharField(blank=True, db_column='thumbnail', max_length=255, null=True)),
                ('instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, to='api.modulos')),
            ],
            options={
                'verbose_name': 'Capacitacion',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id_comentario', models.AutoField(db_column='id_comentario', editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField(db_column='comentario')),
                ('calificacion', models.IntegerField(db_column='calificacion')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True, db_column='fecha_comentario')),
                ('capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='api.capacitaciones')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='estadisticas',
            fields=[
                ('id_estadistica', models.AutoField(db_column='id_estadistica', editable=False, primary_key=True, serialize=False)),
                ('total_cursos_completados', models.IntegerField(db_column='total_cursos_completados', default=0)),
                ('total_horas_aprendizaje', models.IntegerField(db_column='total_horas_aprendizaje', default=0)),
                ('total_insignias', models.IntegerField(db_column='total_insignias', default=0)),
                ('racha_dias', models.IntegerField(db_column='racha_dias', default=0)),
                ('ultima_actividad', models.DateTimeField(blank=True, db_column='ultima_actividad', null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadistica',
                'verbose_name_plural': 'Estadisticas',
                'db_table': 'estadisticas',
            },
        ),
        migrations.CreateModel(
            name='inscripciones',
            fields=[
                ('id_inscripcion', models.AutoField(db_column='id_inscripcion', editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, db_column='fecha_inscripcion')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, db_column='fecha_finalizacion', null=True)),
                ('progreso', models.FloatField(db_column='progreso', default=0.0)),
                ('estado', models.CharField(db_column='estado', max_length=20)),
                ('calificacion', models.FloatField(blank=True, db_column='calificacion', null=True)),
                ('capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='api.capacitaciones')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripciones',
            },
        ),
        migrations.CreateModel(
            name='lecciones',
            fields=[
                ('id_leccion', models.AutoField(db_column='id_leccion', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('contenido', models.TextField(db_column='contenido')),
                ('orden', models.IntegerField(db_column='orden')),
                ('duracion_minutos', models.IntegerField(db_column='duracion_minutos')),
                ('url_recurso', models.URLField(blank=True, db_column='url_recurso', max_length=500, null=True)),
                ('capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='api.capacitaciones')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
                'db_table': 'lecciones',
            },
        ),
        migrations.CreateModel(
            name='notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(db_column='id_notificacion', editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('titulo', models.CharField(db_column='titulo', max_length=200)),
                ('mensaje', models.TextField(db_column='mensaje')),
                ('leida', models.BooleanField(db_column='leida', default=False)),
                ('url_referencia', models.URLField(blank=True, db_column='url_referencia', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='progreso_lecciones',
            fields=[
                ('id_progreso', models.AutoField(db_column='id_progreso', editable=False, primary_key=True, serialize=False)),
                ('completado', models.BooleanField(db_column='completado', default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, db_column='fecha_completado', null=True)),
                ('tiempo_visualizacion', models.IntegerField(db_column='tiempo_visualizacion', default=0)),
                ('inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='api.inscripciones')),
                ('leccion', models.ForeignKey(db_column='id_leccion', on_delete=django.db.models.deletion.CASCADE, to='api.lecciones')),
            ],
            options={
                'verbose_name': 'Progreso Leccion',
                'verbose_name_plural': 'Progreso Lecciones',
                'db_table': 'progreso_lecciones',
            },
        ),
        migrations.CreateModel(
            name='usuario_insignias',
            fields=[
                ('id_usuario_insignia', models.AutoField(db_column='id_usuario_insignia', editable=False, primary_key=True, serialize=False)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True, db_column='fecha_obtencion')),
                ('capacitaciones', models.ForeignKey(blank=True, db_column='id_capacitacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.capacitaciones')),
                ('insignia', models.ForeignKey(db_column='id_insignia', on_delete=django.db.models.deletion.CASCADE, to='api.insignias')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Insignia',
                'verbose_name_plural': 'Usuario Insignias',
                'db_table': 'usuario_insignias',
            },
        ),
    ]
