apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: portal-capacitaciones
  labels:
    app: backend

data:
  DEBUG: "False"
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: portal_capacitacion
  DB_HOST: postgres
  DB_PORT: "5432"
  JWT_ACCESS_TOKEN_LIFETIME: "30"
  JWT_REFRESH_TOKEN_LIFETIME: "7"
  JWT_AUTH_HEADER_TYPE: "Bearer"
  CORS_ALLOW_ALL: "False"
  CORS_ALLOWED_ORIGINS: "https://example.com,https://www.example.com"
  MINIO_ENABLED: "True"
  MINIO_ENDPOINT: http://minio:9000
  MINIO_BUCKET_NAME: media
  MINIO_REGION: us-east-1
  MINIO_ADDRESSING_STYLE: path
  USE_MAILHOG: "False"
  DEFAULT_FROM_EMAIL: no-reply@portalcapacitaciones.com
